### PR TITLE
bugfix Android 2.3.x don't set xhrFields

### PR DESCRIPTION
**Pull request by applezqp**
It is failure to set xhrFields before xhr.open() in Android 2.3.x.

### CODE REVIEW

**Comment by fannyxie** [comment]
Any update on this issue?

**Comment by cloudyan** [comment]
@mwager 
see https://github.com/imweb/mobile/issues/6#issuecomment-170798472

> beforeSend: function(xhr) {
>         try {
>             xhr.withCredentials = true;
>         } catch (e) {
>             var nativeOpen = xhr.open;
>             xhr.open = function() {
>                 var result = nativeOpen.apply(xhr, arguments);
>                 xhr.withCredentials = true;
>                 return result;
>             };
>         }
>     },

**Comment by madrobby** [comment]
We'll no longer be supporting Android 2.3.x in future versions of Zepto. Please keep & update your own fork of Zepto if you need to support these old versions.

**Comment by mislav** [comment]
I've merged this because it helps IE and Windows Mobile compatibility too.

**Pull request closed without merging**
