### PR TITLE
fix #1210

### LINKED ISSUE #1210: 'this' is not equal 'window' anywhere
when use webpack 

```
import $ from 'zepto'

```

https://github.com/madrobby/zepto/blob/v1.2.0/src/amd_layout.js#L6

image

### PR DESCRIPTION
**Pull request by haozi**

### CODE REVIEW

**Comment by mislav** [comment]
What does this actually fix? `this` equals to `window` in a browser setting.

**Comment by haozime** [comment]
https://github.com/madrobby/zepto/issues/1210

**Comment by EnverOsmanov** [comment]
@mislav normally - yes. But with webpack - `this` not equals to `window`.

**Comment by blikblum** [comment]
Currently is not possible to run zepto in node.js plus jsdom.
This PR make it possible.

**Pull request closed without merging**
