### PR TITLE
Use `classList` to manipulate classes in modern browsers

### PR DESCRIPTION
**Pull request by hkongm**
使用高级浏览器提供的classList接口来操作class，在高级浏览器中普遍支持该接口。浏览器内部会优化class操作，减少recalculate和repainting造成的渲染消耗。

### CODE REVIEW

**Comment by Hypher** [comment]
http://jsperf.com/manipulate-css-classlist
Test case created on 6th June 2012 FYI
10 to 20x faster.
Since your code does not differ form the jQuery one, should have the same performance gap.
If you really want a polyfill, https://github.com/eligrey/classList.js available since 2011.
But you dont need a polyfill, you already coded the jquery-like-cross-browser solution. Just test if this.classList exists.

**Comment by mislav** [comment]
Simply testing if `classList` exists [doesn't mean that the browser implementation is complete](https://github.com/eligrey/classList.js/blob/5bdd2929c703d8808561a718011fb30dca517725/classList.js#L196-L218).

However, I support the idea of switching to `classList`. We could avoid cross-browser inconsistencies by avoiding using multiple classnames in a single `add/remove()` call, and by avoiding to use the 2nd argument to `.toggle()` and implementing that toggle logic ourselves.

**Comment by Hypher** [comment]
Yes I think this is the way to go. And that's exactly what @hkongm did in his commits.

**Comment by mislav** [comment]
Yes, except when I look at their commits, the implementation is not working. The code in this PR is routinely using `this.classList` in cases when `this` doesn't even refer to a DOM node, but to other things. We might open a new PR for this.

**Pull request closed without merging**
