### PR TITLE
bugfix Open XHR before setting XHR fields

### PR DESCRIPTION
**Pull request by mscienski**
Since #935 hasn't moved in over a year, this PR should resolve the comment about xhr fields being set on onAjaxBeforeSend still throwing an error.

### CODE REVIEW

**Comment by mislav** [comment]
Which platforms other than Android 2.3 does the original bug still affect, if any?

I'm a little concerned about replacing the actual XHR object with a fake one that contains its properties.

**Comment by mscienski** [comment]
It affects the stock browser on Android up to 4.2.

The biggest concern with the copied object would be triggering the ajaxSend event with it. If ajaxSend should be triggered with the original xhr, then the trigger can be moved from ajaxBeforeSend to $.ajax.

**Comment by mscienski** [comment]
Fat fingered the close button on accident.

**Comment by mscienski** [comment]
Updated the PR. Now it only uses the copy to check whether the call to beforeSend returns false, and if the consumer sets properties on the xhr copy in beforeSend, those properties will be copied after the xhr is opened.

**Comment by mislav** [comment]
I've merged the original PR for Android and Windows Mobile compatibility, and am closing this as a non-issue anymore. Thanks for all the investigative work you did here.

Note that `beforeSend: function(xhr) { xhr.withCredentials = true }` still won't work in some browsers (most notably IE and Windows Mobile), but it doesn't work perfectly in jQuery either (the setting is ignored). So, you must use `xhrFields` for that purpose.

**Pull request closed without merging**
