### PR TITLE
Adding isNumeric to Zepto #847

### PR DESCRIPTION
**Pull request by dperrymorrow**
In response to issue #847 pull request for adding isNumeric.

### CODE REVIEW

**Comment by mtomov** [comment]
Can you please merge the function as [owl carousel](http://www.owlcarousel.owlgraphic.com/) also depends on it.

**Comment by madrobby** [comment]
Note that the jQuery expression for this is `!isNaN(parseFloat(obj)) && isFinite(obj)`. `isFinite` is a JavaScript native global function, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isFinite.

If we want to add this we should probably use the same implementation and port the tests from jQuery on this (I haven't looked at them).

**Comment by jcampbell05** [comment]
Any progress on this ?

**Comment by madrobby** [comment]
Closing this because there was no response to our questions in a while. Feel free to reopen with the requested information!

**Pull request closed without merging**
